// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kalman_smoother_cpp
NumericVector kalman_smoother_cpp(NumericVector y, int degree, double H, NumericVector Q, double init_state, double init_var);
RcppExport SEXP _fastImpute_kalman_smoother_cpp(SEXP ySEXP, SEXP degreeSEXP, SEXP HSEXP, SEXP QSEXP, SEXP init_stateSEXP, SEXP init_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type init_state(init_stateSEXP);
    Rcpp::traits::input_parameter< double >::type init_var(init_varSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_smoother_cpp(y, degree, H, Q, init_state, init_var));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastImpute_kalman_smoother_cpp", (DL_FUNC) &_fastImpute_kalman_smoother_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastImpute(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
