# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ Kalman Smoother Engine
NULL

kalman_smoother_cpp <- function(y, degree, H, Q, init_state, init_var) {
    .Call(`_fastImpute_kalman_smoother_cpp`, y, degree, H, Q, init_state, init_var)
}

